/**:
  ros__parameters:
    localization:
      type: diagnostic_aggregator/AnalyzerGroup
      path: localization
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": localization_topic_status"]
              timeout: 1.0

        performance_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: performance_monitoring
          analyzers:
            matching_score:
              type: diagnostic_aggregator/GenericAnalyzer
              path: matching_score
              contains: ["ndt_scan_matcher"]
              timeout: 1.0

            localization_accuracy:
              type: diagnostic_aggregator/GenericAnalyzer
              path: localization_accuracy
              contains: [": localization_accuracy"]
              timeout: 1.0

            lane_departure_risk:
              type: diagnostic_aggregator/GenericAnalyzer
              path: lane_departure_risk
              contains: [": lane_departure_risk"]
              timeout: 0.3

            stopline_overrun_risk:
              type: diagnostic_aggregator/GenericAnalyzer
              path: stopline_overrun_risk
              contains: [": stopline_overrun_risk"]
              timeout: 0.3
