/**:
  ros__parameters:
    sensing:
      type: diagnostic_aggregator/AnalyzerGroup
      path: sensing
      analyzers:
        performance_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: performance_monitoring
          analyzers:
            concat_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: concat_status
              timeout: 1.0
